// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_stream from "./routes/api/stream.ts";
import * as $api_tasks from "./routes/api/tasks.ts";
import * as $index from "./routes/index.tsx";
import * as $TaskInput from "./islands/TaskInput.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/stream.ts": $api_stream,
    "./routes/api/tasks.ts": $api_tasks,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/TaskInput.tsx": $TaskInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
